### ISSUE TITLE
Component management

### ISSUE THREAD

**Issue by Hazem-Gamall** [Charged-Entertainment/Charged-Learning#20]
- [x] Add `LevelComponenets`.
- [x] Add `LiveComponents`.
- [x] Add a `Property` class that contains properties of the electric components.
- [x] Handle the `RevealState` property of  a component.
- [x] Create an entity that generates the ui elements for level components.
- [x] Configure the UI interactions.

**Comment by nourgaser** [comment]
Initial working version merged into #15.
