### ISSUE TITLE
Multi-meter red probe cannot be moved to current measurement slots on the multimeter

### ISSUE THREAD

**Issue by 1Rooky** [Charged-Entertainment/Charged-Learning#28]
![image](https://user-images.githubusercontent.com/76395068/218247644-848c5480-2fdb-44f1-a01a-4388fbfba855.png)

**Comment by nourgaser** [comment]
Please explain further what you mean by this. @1Rooky

**Comment by 1Rooky** [comment]
The red and blue wires are fixed. 
Their position cannot be changed from COM to mA and  etc.

**Comment by nourgaser** [comment]
No longer needed. See #40.
