### ISSUE TITLE
terminal lags 

### ISSUE THREAD

**Issue by 1Rooky** [Charged-Entertainment/Charged-Learning#31]
https://user-images.githubusercontent.com/76395068/218248524-f37704ba-e3bc-4a59-b5fd-b7fc70f9414a.mp4

**Comment by Hazem-Gamall** [comment]
Fixed in commit a5bced601eae627d55b3746a3a6f1dc8747ca15e

**Comment by Hazem-Gamall** [comment]
Fixed in commit a5bced601eae627d55b3746a3a6f1dc8747ca15e
