### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by Hazem-Gamall** [Charged-Entertainment/Charged-Learning#4]
**Features needed**
- [x] Grid @Hazem-Gamall 
- [x] Selection #5 @Hazem-Gamall @nourgaser 
- [x] Move @nourgaser 
- [x] Zoom @husseinjunior 
- [x] Pan @husseinjunior
- [x] Flip (Vertical/Horizontal) @nourgaser 
- [x] Rotate (Left/Right) @nourgaser 
- [x] Copy / Cut @nourgaser 
- [x] Paste @nourgaser 

![Image](https://user-images.githubusercontent.com/54468523/211617289-7c904dfb-1ed4-4170-ae06-5cde5943c00e.png)

**Comment by nourgaser** [comment]
Done. https://github.com/Charged-Entertainment/Charged-Learning/commit/6aa7640dd4e5b91aed7a9aa6a538f2b0578b2a6d#diff-d1d21d9fd07c5397cb1ddb97e15892cddb7e406c6a6c6322bd7677c612641e6a
