### ISSUE TITLE
Multi-meter re-design

### ISSUE THREAD

**Issue by nourgaser** [Charged-Entertainment/Charged-Learning#40]
Should be an auto-range multimeter and the probes should have terminals just like normal components.

- [x] New UI design on figma. @1Rooky 
- [x] Re-implement in the game. @Hazem-Gamall 
    - [x] Probes should have terminals like normal components.

**Comment by 1Rooky** [comment]
![image](https://user-images.githubusercontent.com/76395068/218436166-f5b9a0a6-a45b-46f6-a59c-73364d7cb332.png)


https://www.figma.com/file/cPA8Ns5kRBAJkpJfEa3K4F/Game-Design-%26-UI?node-id=9%3A2&t=3hg2sOitNDcIKW59-0

Done .. :+1:

**Comment by nourgaser** [comment]
Done on 33c0bdc.
