### ISSUE TITLE
Connecting with Terminals creates a mess

### ISSUE THREAD

**Issue by 1Rooky** [Charged-Entertainment/Charged-Learning#52]
#39 

connecting components with terminals is a good idea unless it is in the wiring mood. 
as now moving components around makes a lot of unintentional connections that makes a big mess. 
 +
different issue: the led in the end of the idea appeared behind the battery.

https://user-images.githubusercontent.com/76395068/218306805-33b60ea5-9a4d-4fdd-841b-817965810013.mp4

**Comment by nourgaser** [comment]
Not a bug, they just spawn on top of each other so the terminals collide and connect, #33 will fix it.

**Comment by nourgaser** [comment]
#53 kind of addresses this as well.
